# Generated by Django 6.0.2 on 2026-04-14 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0043_remove_bomline_bom_remove_bomline_created_by_and_more'),
        ('rdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de categoria')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='FractionHtsus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=15, verbose_name='Código')),
                ('nico', models.CharField(blank=True, max_length=2, null=True, verbose_name='NICO')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fracción HTSUS',
                'verbose_name_plural': 'Fracciones HTSUS',
                'db_table': 'fraction_htsus',
                'unique_together': {('code', 'nico')},
            },
        ),
        migrations.CreateModel(
            name='FractionMx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('cal_imp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Importación')),
                ('cal_exp', models.CharField(blank=True, max_length=100, null=True, verbose_name='Exportación')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fracción Arancelaria Mexicana',
                'verbose_name_plural': 'Fracciones Arancelarias Mexicana',
                'db_table': 'fraction_mx',
            },
        ),
        migrations.CreateModel(
            name='FractionUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fracción de usa',
                'verbose_name_plural': 'Fracciones de usa',
                'db_table': 'fraction_us',
            },
        ),
        migrations.CreateModel(
            name='FractionUsExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fracción de usa para exportación',
                'verbose_name_plural': 'Fracciones de usa para exportación',
                'db_table': 'fraction_us_exp',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Codigo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('description_us', models.TextField(blank=True, null=True, verbose_name='Descripción (Ing)')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('nafta', models.BooleanField(default=False, verbose_name='Nafta')),
                ('type', models.CharField(choices=[('M', 'Material'), ('F', 'Producto Terminado'), ('A', 'Activo')], default='M', max_length=1, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('N', 'Nuevos'), ('U', 'Usados'), ('R', 'Reconstruidos'), ('RM', 'Remanufacturados')], default='N', max_length=2, verbose_name='Estado de la mercancía')),
                ('weight_pack', models.FloatField(default=0.0, verbose_name='Peso de empaque (kg)')),
                ('weight_mat', models.FloatField(default=0.0, verbose_name='Peso de material (kg)')),
                ('weight', models.FloatField(default=0.0, verbose_name='Peso (kg)')),
                ('fac_po', models.FloatField(default=0.0, verbose_name='Factor de compra')),
                ('fac_co', models.FloatField(default=0.0, verbose_name='Factor comercial')),
                ('fac_rate', models.FloatField(default=0.0, help_text='Factor de tarifa de comercio exterior', verbose_name='Factor tarifa de com. exterior')),
                ('fac_bom', models.FloatField(default=0.0, verbose_name='Factor en bom')),
                ('fac_rate_us', models.FloatField(default=0.0, verbose_name='Factor de tarifa us')),
                ('fac_so', models.FloatField(default=0.0, verbose_name='Factor de venta')),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Costo unitario')),
                ('cost_av', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado')),
                ('uc_mat_or', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Materia prima originario')),
                ('uc_mat_nor', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Materia prima no originario')),
                ('uc_pack_or', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Empaques originario')),
                ('uc_pack_nor', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Empaques no originario')),
                ('uc_or_stot', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Sub-Total originario')),
                ('uc_nor_stot', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Sub-Total no originario')),
                ('cav_ind', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado indirectos')),
                ('cav_dir', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado directos')),
                ('cav_nat', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado nacionales')),
                ('cost_tot', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='costo total')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='Categoria')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.country', verbose_name='Pais')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fraction_htsus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.fractionhtsus', verbose_name='Fracción HTSUS')),
                ('fraction_mx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.fractionmx', verbose_name='Fracción MX')),
                ('fraction_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.fractionus', verbose_name='Fracción US')),
                ('fraction_us_exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.fractionusexp', verbose_name='Fracción US exportación')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.sector', verbose_name='Sector')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rdata.partner', verbose_name='Proveedor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_supplier',
            },
        ),
        migrations.CreateModel(
            name='ProductUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('factor', models.FloatField(default=0.0, verbose_name='Factor')),
                ('base', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Base')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidades de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'product_uom',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fac_bom_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productuom', verbose_name='Unidad de medida de bom'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_co_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productuom', verbose_name='Unidad de medida de factor comercial'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_po_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productuom', verbose_name='Unidad de medida de factor de compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_rate_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productuom', verbose_name='Unidad de medida de tarifa de comercio exterior'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_rate_us_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productuom', verbose_name='Unidad de medida de factor comercial'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_so_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.productuom', verbose_name='Unidad de medida de venta'),
        ),
    ]
