# Generated by Django 6.0.2 on 2026-02-19 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsupplier',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de lista')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lista de materiales',
                'verbose_name_plural': 'Listas de materiales',
                'db_table': 'bom',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Bomline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('bom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.bom', verbose_name='Bom')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Lista de materiales',
                'verbose_name_plural': 'Listas de materiales',
                'db_table': 'bom_line',
            },
        ),
    ]
