# Generated by Django 6.0.2 on 2026-02-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_productsupplier_product_id_bom_bomline'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsupplier',
            table='product_supplier',
        ),
    ]
