# Generated by Django 6.0.2 on 2026-02-19 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_productsupplier_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bom',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='bomline',
            old_name='bom_id',
            new_name='bom',
        ),
        migrations.RenameField(
            model_name='bomline',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productsupplier',
            old_name='product_id',
            new_name='product',
        ),
    ]
