# Generated by Django 6.0.2 on 2026-02-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_partner_productsupplier_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de categoria')),
            ],
            options={
                'verbose_name': 'Sector autorizado',
                'verbose_name_plural': 'Sectores autorizados',
                'db_table': 'sector',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre de categoria'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
