# Generated by Django 6.0.2 on 2026-02-26 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_bom_created_by_alter_bom_updated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_av',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.country', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_us',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción (Ing)'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_po',
            field=models.FloatField(default=0.0, verbose_name='Factor de compra'),
        ),
        migrations.AddField(
            model_name='product',
            name='fraction_htsus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionhtsus', verbose_name='Fracción HTSUS'),
        ),
        migrations.AddField(
            model_name='product',
            name='fraction_mx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionmx', verbose_name='Fracción MX'),
        ),
        migrations.AddField(
            model_name='product',
            name='fraction_us_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionusexp', verbose_name='Fracción US Exportación'),
        ),
        migrations.AddField(
            model_name='product',
            name='nafta',
            field=models.BooleanField(default=False, verbose_name='Nafta'),
        ),
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('M', 'Material'), ('F', 'Producto Terminado'), ('A', 'Activo')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=0.0, verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_mat',
            field=models.FloatField(default=0.0, verbose_name='Peso de material (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_pack',
            field=models.FloatField(default=0.0, verbose_name='Peso de empaque (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='productsupplier',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='ProductUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de categoria')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unidadde medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'product_uom',
            },
        ),
    ]
