# Generated by Django 6.0.2 on 2026-02-26 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_product_cost_product_cost_av_product_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fac_po_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.productuom', verbose_name='Unidad de medida de factor de compra'),
        ),
    ]
