# Generated by Django 6.0.2 on 2026-02-26 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_product_fac_po_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fac_po_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productuom', verbose_name='Unidad de medida de factor de compra'),
        ),
    ]
