# Generated by Django 6.0.2 on 2026-02-26 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_product_fac_po_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fac_bom',
            field=models.FloatField(default=0.0, verbose_name='Factor en bom'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_bom_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productuom', verbose_name='Unidad de medida de bom'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_co',
            field=models.FloatField(default=0.0, verbose_name='Factor comercial'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_co_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.productuom', verbose_name='Unidad de medida de factor comercial'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_rate',
            field=models.FloatField(default=0.0, verbose_name='Factor de tarifa en comercio exterior'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_rate_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productuom', verbose_name='Unidad de medida de de tarifa de comercio exterior'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_rate_us',
            field=models.FloatField(default=0.0, verbose_name='Factor de tarifa us'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_rate_us_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productuom', verbose_name='Unidad de medida de factor comercial'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_so',
            field=models.FloatField(default=0.0, verbose_name='Factor de venta'),
        ),
        migrations.AddField(
            model_name='product',
            name='fac_so_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productuom', verbose_name='Unidad de medida de venta'),
        ),
    ]
