# Generated by Django 6.0.2 on 2026-03-02 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_fractionusexp_options_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fac_po',
            field=models.FloatField(default=0.0, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_htsus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionhtsus', verbose_name='Fracc. HTSUS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_mx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionmx', verbose_name='Fracc. MX'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionus', verbose_name='Fracc. US'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_us_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionusexp', verbose_name='Fracc. US Exportación'),
        ),
    ]
