# Generated by Django 6.0.2 on 2026-03-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_product_fac_po_alter_product_fraction_htsus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fac_po',
            field=models.FloatField(default=0.0, verbose_name='Factor de compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_htsus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionhtsus', verbose_name='Fracción HTSUS'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_mx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionmx', verbose_name='Fracción MX'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionus', verbose_name='Fracción US'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fraction_us_exp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.fractionusexp', verbose_name='Fracción US exportación'),
        ),
    ]
