# Generated by Django 6.0.2 on 2026-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_product_fac_po_alter_product_fraction_htsus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cd_av_dir',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado directos'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_av_ind',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado indirectos'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_av_nat',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado nacionales'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_mat_nor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Materia prima no originario'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_mat_or',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Materia prima originario'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_pack_nor',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Empaques no originario'),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_pack_or',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Empaques originario'),
        ),
    ]
