# Generated by Django 6.0.2 on 2026-03-04 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_product_status_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Nuevos'), ('U', 'Usados'), ('R', 'Reconstruidos'), ('RM', 'Remanufacturados')], default='N', max_length=2, verbose_name='Estado de la mercancía.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fac_rate_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.productuom', verbose_name='Unidad de medida de tarifa de comercio exterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('M', 'Material'), ('F', 'Producto Terminado'), ('A', 'Activo')], default='M', max_length=1, verbose_name='Tipo'),
        ),
    ]
