# Generated by Django 6.0.2 on 2026-03-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_product_status_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productuom',
            options={'verbose_name': 'Unidades de medida', 'verbose_name_plural': 'Unidades de medida'},
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
