# Generated by Django 6.0.2 on 2026-03-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_productuom_options_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(choices=[(True, 'Material'), (False, 'Producto Terminado')], default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
