# Generated by Django 6.0.2 on 2026-03-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_category_active_alter_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
    ]
