# Generated by Django 6.0.2 on 2026-03-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_category_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='country',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='fractionhtsus',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='fractionmx',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='fractionus',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='fractionusexp',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='productuom',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='sector',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
    ]
