# Generated by Django 6.0.2 on 2026-03-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_bom_active_country_active_fractionhtsus_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
