# Generated by Django 6.0.2 on 2026-03-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_code_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='productuom',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
