# Generated by Django 6.0.2 on 2026-03-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_country_name_alter_product_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fractionmx',
            options={'verbose_name': 'Fracción Arancelaria Mexicana', 'verbose_name_plural': 'Fracciones Arancelarias Mexicana'},
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='code_fiii',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Clave SAAI FIII'),
        ),
        migrations.AddField(
            model_name='country',
            name='code_m3',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Clave SAAI M3'),
        ),
        migrations.AddField(
            model_name='fractionhtsus',
            name='nico',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='NICO'),
        ),
        migrations.AddField(
            model_name='fractionmx',
            name='cal_exp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exportación'),
        ),
        migrations.AddField(
            model_name='fractionmx',
            name='cal_imp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Importación'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fractionhtsus',
            name='name',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='fractionmx',
            name='name',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código'),
        ),
    ]
