# Generated by Django 6.0.2 on 2026-03-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_fractionmx_options_remove_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fractionhtsus',
            name='code',
            field=models.CharField(max_length=15, verbose_name='Código'),
        ),
        migrations.AlterUniqueTogether(
            name='fractionhtsus',
            unique_together={('code', 'nico')},
        ),
    ]
