# Generated by Django 6.0.2 on 2026-03-23 23:03

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_product_cd_av_stot_remove_product_cd_av_tot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cd_av_stot',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cd_av_ind'), '+', models.F('cd_av_dir')), '+', models.F('cd_av_nat')), output_field=models.DecimalField(decimal_places=4, max_digits=10)),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_av_tot',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('cd_mat_nor'), '+', models.F('cd_pack_nor')), '+', models.F('cd_mat_or')), '+', models.F('cd_pack_or')), '+', models.F('cd_av_ind')), '+', models.F('cd_av_dir')), '+', models.F('cd_av_nat')), output_field=models.DecimalField(decimal_places=4, max_digits=10)),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_nor_stot',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cd_mat_nor'), '+', models.F('cd_pack_nor')), output_field=models.DecimalField(decimal_places=4, max_digits=10)),
        ),
        migrations.AddField(
            model_name='product',
            name='cd_or_stot',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('cd_mat_or'), '+', models.F('cd_pack_or')), output_field=models.DecimalField(decimal_places=4, max_digits=10)),
        ),
    ]
