# Generated by Django 6.0.2 on 2026-03-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_product_cd_av_stot_product_cd_av_tot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cd_or_stot',
        ),
    ]
