# Generated by Django 6.0.2 on 2026-03-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_product_cd_or_stot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cd_av_dir',
            new_name='cav_dir',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cd_av_ind',
            new_name='cav_ind',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cd_av_nat',
            new_name='cav_nat',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cd_mat_nor',
            new_name='uc_mat_nor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cd_mat_or',
            new_name='uc_mat_or',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cd_pack_nor',
            new_name='uc_pack_nor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cd_pack_or',
            new_name='uc_pack_or',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cd_av_stot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cd_av_tot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cd_nor_stot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_av',
        ),
        migrations.AddField(
            model_name='product',
            name='cav_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='cav_tot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='uc_nor_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='uc_or_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='uc_tot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10),
        ),
    ]
