# Generated by Django 6.0.2 on 2026-03-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_rename_cd_av_dir_product_cav_dir_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cav_stot',
            new_name='cost_tot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cav_tot',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_av',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10, verbose_name='Valor agregado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uc_nor_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10, verbose_name='Valor agregado directos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uc_or_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10, verbose_name='Sub-Total originario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uc_tot',
            field=models.DecimalField(decimal_places=4, default=0.0, editable=False, max_digits=10, verbose_name='Costo Unitario'),
        ),
    ]
