# Generated by Django 6.0.2 on 2026-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_cav_stot_product_cost_tot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uc_tot',
        ),
        migrations.AddField(
            model_name='productuom',
            name='base',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Base'),
        ),
        migrations.AddField(
            model_name='productuom',
            name='factor',
            field=models.FloatField(default=0.0, verbose_name='Factor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_av',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Valor agregado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_tot',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='costo total'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uc_nor_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Sub-Total no originario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uc_or_stot',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, verbose_name='Sub-Total originario'),
        ),
    ]
