# Generated by Django 6.0.2 on 2026-04-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_remove_product_uc_tot_productuom_base_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_num',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='partner',
            name='address_num_int',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero interior'),
        ),
        migrations.AddField(
            model_name='partner',
            name='agency',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Agencia'),
        ),
        migrations.AddField(
            model_name='partner',
            name='alr',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ALR'),
        ),
        migrations.AddField(
            model_name='partner',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='partner',
            name='card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gafete'),
        ),
        migrations.AddField(
            model_name='partner',
            name='card_exp_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de gafette'),
        ),
        migrations.AddField(
            model_name='partner',
            name='card_fast_exp_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia tarjeta fast'),
        ),
        migrations.AddField(
            model_name='partner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.country', verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='partner',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='partner',
            name='customer',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='partner',
            name='driver',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Chofer'),
        ),
        migrations.AddField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer apellido'),
        ),
        migrations.AddField(
            model_name='partner',
            name='gender',
            field=models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], default='1', max_length=1, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='partner',
            name='irs',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='I.R.S.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='license_exp_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Vigencia de licencia'),
        ),
        migrations.AddField(
            model_name='partner',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='partner',
            name='off_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AddField(
            model_name='partner',
            name='patent',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Patente'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='partner',
            name='po_box',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='P.O. box'),
        ),
        migrations.AddField(
            model_name='partner',
            name='registration_dt',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='partner',
            name='repr',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Representante legal'),
        ),
        migrations.AddField(
            model_name='partner',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='partner',
            name='second_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AddField(
            model_name='partner',
            name='supplier',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='partner',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='C.P.'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'state',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.state', verbose_name='Estado'),
        ),
    ]
