# Generated by Django 6.0.2 on 2026-04-05 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_partner_active_partner_address_partner_address_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='legal_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'repr': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='agency',
            field=models.BooleanField(default=False, verbose_name='Es agencia'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='customer',
            field=models.BooleanField(default=True, verbose_name='Es cliente'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='driver',
            field=models.BooleanField(default=False, verbose_name='Es chofer'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='repr',
            field=models.BooleanField(default=False, verbose_name='Es representante legal'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='supplier',
            field=models.BooleanField(default=True, verbose_name='Es proveedor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fac_rate',
            field=models.FloatField(default=0.0, help_text='Factor de tarifa de comercio exterior', verbose_name='Factor tarifa de com. exterior'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('N', 'Nuevos'), ('U', 'Usados'), ('R', 'Reconstruidos'), ('RM', 'Remanufacturados')], default='N', max_length=2, verbose_name='Estado de la mercancía'),
        ),
    ]
