# Generated by Django 6.0.2 on 2026-04-07 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_partner_legal_rep_alter_partner_agency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='agency',
            new_name='is_agency',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='customer',
            new_name='is_customer',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='driver',
            new_name='is_driver',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='repr',
            new_name='is_repr',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='supplier',
            new_name='is_supplier',
        ),
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(blank=True, limit_choices_to={'company': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_representative_for', to='base.partner', verbose_name='Compañia'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_company',
            field=models.BooleanField(default=False, verbose_name='Es compañia'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='legal_rep',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_repr': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_partners', to='base.partner', verbose_name='Representante legal'),
        ),
    ]
