# Generated by Django 6.0.2 on 2026-04-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_rename_agency_partner_is_agency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='company',
            new_name='partner',
        ),
    ]
