# Generated by Django 6.0.2 on 2026-04-14 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0043_remove_bomline_bom_remove_bomline_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('first_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Primer apellido')),
                ('second_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('irs', models.CharField(blank=True, max_length=15, null=True, verbose_name='I.R.S.')),
                ('alr', models.CharField(blank=True, max_length=15, null=True, verbose_name='ALR')),
                ('patent', models.CharField(blank=True, max_length=15, null=True, verbose_name='Patente')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefono')),
                ('mobile', models.CharField(blank=True, max_length=30, null=True, verbose_name='Mobile')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='E-mail')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='Website')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion')),
                ('address_num', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero')),
                ('address_num_int', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero interior')),
                ('zip', models.CharField(blank=True, max_length=20, null=True, verbose_name='C.P.')),
                ('po_box', models.CharField(blank=True, max_length=20, null=True, verbose_name='P.O. box')),
                ('card', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gafete')),
                ('gender', models.CharField(choices=[('1', 'Hombre'), ('2', 'Mujer')], default='1', max_length=1, verbose_name='Genero')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('registration_dt', models.DateField(blank=True, null=True, verbose_name='Fecha de alta')),
                ('off_dt', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('license_exp_dt', models.DateField(blank=True, null=True, verbose_name='Vigencia de licencia')),
                ('card_exp_dt', models.DateField(blank=True, null=True, verbose_name='Vigencia de gafette')),
                ('card_fast_exp_dt', models.DateField(blank=True, null=True, verbose_name='Vigencia tarjeta fast')),
                ('is_customer', models.BooleanField(default=True, verbose_name='Es cliente')),
                ('is_supplier', models.BooleanField(default=True, verbose_name='Es proveedor')),
                ('is_repr', models.BooleanField(default=False, verbose_name='Es representante legal')),
                ('is_driver', models.BooleanField(default=False, verbose_name='Es chofer')),
                ('is_agency', models.BooleanField(default=False, verbose_name='Es agencia')),
                ('is_company', models.BooleanField(default=False, verbose_name='Es compañia')),
                ('active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False, verbose_name='Activo')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.country', verbose_name='Pais')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('legal_rep', models.ForeignKey(blank=True, limit_choices_to={'is_repr': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_representative_for', to='rdata.partner', verbose_name='Representante legal')),
                ('partner', models.ForeignKey(blank=True, limit_choices_to={'is_company': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_partners', to='rdata.partner', verbose_name='Compañia')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.state', verbose_name='Estado')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'db_table': 'partner',
            },
        ),
    ]
